# DO NOT EDIT - generated by packages/shared codegen.
# Source of truth: packages/shared/src/schemas/*.ts (Zod).
# Regenerate via: pnpm --filter @aeogen/shared build


from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class Site(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    workspace_id: UUID
    url: AnyUrl
    default_language: Literal["tr", "en", "de", "fr", "es"]
    sector: Annotated[str | None, Field(max_length=120, min_length=1)]
