# DO NOT EDIT - generated by packages/shared codegen.
# Source of truth: packages/shared/src/schemas/*.ts (Zod).
# Regenerate via: pnpm --filter @aeogen/shared build


from __future__ import annotations

from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Workspace(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    org_id: UUID
    name: Annotated[str, Field(max_length=120, min_length=1)]
    slug: Annotated[str, Field(max_length=120, min_length=1, pattern="^[a-z0-9-]+$")]
    created_at: datetime
