import { spawn } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMA_DIR = resolve(__dirname, '../../dist/schemas');
const PY_OUT_DIR = resolve(__dirname, '../../python/aeogen_shared');
const PKG_ROOT = resolve(__dirname, '../..');

const GENERATED_HEADER = `# DO NOT EDIT - generated by packages/shared codegen.
# Source of truth: packages/shared/src/schemas/*.ts (Zod).
# Regenerate via: pnpm --filter @aeogen/shared build
`;

interface Job {
  schemaFile: string;
  outFile: string;
  className: string;
}

const JOBS: Job[] = [
  { schemaFile: 'site.schema.json', outFile: 'site.py', className: 'Site' },
  {
    schemaFile: 'workspace.schema.json',
    outFile: 'workspace.py',
    className: 'Workspace',
  },
];

const UV_EXECUTABLE = process.platform === 'win32' ? 'uv.exe' : 'uv';

function runUv(args: string[]): Promise<void> {
  return new Promise((res, rej) => {
    // shell:false so multi-line --custom-file-header argument is passed
    // verbatim to uv without cmd.exe re-splitting it on newlines.
    const p = spawn(UV_EXECUTABLE, args, {
      cwd: PKG_ROOT,
      stdio: 'inherit',
      shell: false,
    });
    p.on('error', (err) => rej(err));
    p.on('exit', (code) =>
      code === 0 ? res() : rej(new Error(`uv ${args.join(' ')} exited ${code}`))
    );
  });
}

interface JsonSchemaRoot {
  required?: string[];
  properties?: Record<string, { type?: unknown }>;
}

/**
 * Strip ` = None` trailing default on fields that are nullable AND required
 * in the source JSON Schema.
 *
 * datamodel-code-generator (v0.26) adds `= None` to every nullable field even
 * when JSON Schema lists it in `required`. That silently turns the field into
 * an optional input on the Python side and breaks parity with Zod, which
 * still rejects missing required-nullable keys. We post-process the generated
 * file with a deterministic regex to drop the default while keeping `T | None`
 * as the type annotation. Optional-nullable fields are left untouched.
 */
async function stripRequiredNullableDefault(
  pyPath: string,
  schemaPath: string
): Promise<void> {
  const schemaRaw = await readFile(schemaPath, 'utf8');
  const schema = JSON.parse(schemaRaw) as JsonSchemaRoot;
  const required = new Set(schema.required ?? []);
  const props = schema.properties ?? {};

  const requiredNullableFields = Object.entries(props)
    .filter(([name, sub]) => {
      if (!required.has(name)) return false;
      const t = sub.type;
      return Array.isArray(t) && t.includes('null');
    })
    .map(([name]) => name);

  if (requiredNullableFields.length === 0) return;

  let content = await readFile(pyPath, 'utf8');
  let mutated = false;
  for (const fieldName of requiredNullableFields) {
    const re = new RegExp(`^(\\s+${fieldName}:[^\\n]*) = None$`, 'gm');
    const replaced = content.replace(re, '$1');
    if (replaced !== content) {
      content = replaced;
      mutated = true;
    }
  }
  if (mutated) await writeFile(pyPath, content, 'utf8');
}

for (const job of JOBS) {
  const input = resolve(SCHEMA_DIR, job.schemaFile);
  const output = resolve(PY_OUT_DIR, job.outFile);
  await runUv([
    'run',
    'datamodel-codegen',
    '--input',
    input,
    '--input-file-type',
    'jsonschema',
    '--output',
    output,
    '--output-model-type',
    'pydantic_v2.BaseModel',
    '--target-python-version',
    '3.12',
    '--use-schema-description',
    '--use-field-description',
    '--use-standard-collections',
    '--use-union-operator',
    '--enum-field-as-literal',
    'all',
    '--use-double-quotes',
    '--use-annotated',
    '--collapse-root-models',
    '--disable-timestamp',
    '--custom-file-header',
    GENERATED_HEADER,
  ]);
  await stripRequiredNullableDefault(output, input);
  console.log(`codegen: ${job.outFile}`);
}
